### ISSUE TITLE
The `window-height` value

### ISSUE THREAD

**Issue by toyboot4e** [aikrahguzar/consult-hoogle#1]
Hi, thanks for sharing `consult-hoogle`!

Currently the side window's [window-height is `(+ 3 vertico-count)`](https://github.com/aikrahguzar/consult-hoogle/blob/187aa5461731ce1e0fcce43cf1114811fdabf408/consult-hoogle.el#L166), but it might rather want to be `,(+ 3 vertico-count vertico-count)`.

> NOTE: I'm only considering `vertico`  use case.

# Example

I have a frame with `total-window-size` 50. My `vertico-count` (vertico window height) is `20`.

## With the default setting (`,(+ 3 vertico-count)`)

With the default setting, the ` *Hoogle Documentation*` seem to have the half size of rest the `30`:

<img width="1920" alt="consult-hoogle-default" src="https://user-images.githubusercontent.com/47905926/200151893-de532b6d-49cf-4cfc-8f05-f7aaf52dfdcc.png">

but I want my ` *Hoogle Documentation*` window to have size of at least `20` (or `,(+ 3 vertico-count)` = `23`).

## With a tweaked setting (`40`)

I tried changing `window-height` to be `40` and ran `M-x consult-hoogle`:

<img width="1919" alt="consult-hoogle-40-default" src="https://user-images.githubusercontent.com/47905926/200151983-6118f5b9-3c28-4896-bb1e-ae98fdaedb17.png">

And then searched:

<img width="1920" alt="consult-hoogle-40" src="https://user-images.githubusercontent.com/47905926/200151992-5bf5ecd9-1598-43be-be2f-2a84f3b98b05.png">

So it seems like the `window-height` needs to be the consult window size + the size of ` *Hoogle Documentation*` window. And the window size might rather want to be `,(+ (+ 3 vertico-count) vertico-count)`.

**Comment by toyboot4e** [comment]
The bad point of `,(+ 3 vertico-count vertico-count)` is that the empty preview window always occupies the space on open. Others might not like it.

It doesn't need to be the default, I'm just sharing how to force a bigger preview window. Thank you :)

**Comment by aikrahguzar** [comment]
The use of `vertico-count` is not great. I need to wrap it with at least `bound-and-true-p` and supply some default value because this package is not supposed to depend on `vertico` only `consult`.

But to the issue at hand there aren't many customization options in this package and some should be added. A customizable display action can be one of them but I have mixed feelings about it since the same can be achieved by adding an entry to `display-buffer-alist` and it seems like a good thing to let that variable handle everything. On the other hand, `display-buffer-alist` is very completed and by providing a customizable default action, users can at least change the simple stuff like `window-height` easily without knowing about the whole machinery.

I will probably change this soon but it is good that there is a workaround.

**Comment by toyboot4e** [comment]
I didn’t know `window-height` can be a function. It would satisfy all of my needs, thanks!

The default system design sounds hard. Some might not even know dotted pairs and alist! But I like the Emacs learning process where I’m forced to be a power user. Others might have the same taste.
